//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RState
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_User_Pictures
    {
        public int Id { get; set; }
        public int PicId { get; set; }
        public int UserId { get; set; }
    
        public virtual Tb_Pictures Tb_Pictures { get; set; }
        public virtual Tb_Users_Info Tb_Users_Info { get; set; }
    }
}
